jump-to-django/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

jump-to-django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pybo/", include("pybo.urls")),
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),
]

jump-to-django/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = "pybo"

urlpatterns = [
    # base views
    path("", base_views.index, name="index"),
    path("<int:question_id>/", base_views.detail, name="detail"),
    # question views
    path("question/create/", question_views.question_create, name="question_create"),
    path(
        "question/modify/<int:question_id>/",
        question_views.question_modify,
        name="question_modify",
    ),
    path(
        "question/delete/<int:question_id>/",
        question_views.question_delete,
        name="question_delete",
    ),
    # answer views
    path(
        "answer/create/<int:question_id>/",
        answer_views.answer_create,
        name="answer_create",
    ),
    path(
        "answer/modify/<int:answer_id>/",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    path(
        "answer/delete/<int:answer_id>/",
        answer_views.answer_delete,
        name="answer_delete",
    ),
]

jump-to-django/common/models.py
from django.db import models

# Create your models here.

jump-to-django/pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    subject = models.CharField(help_text="질문의 제목", max_length=200)
    content = models.TextField(help_text="질문의 내용")
    modify_date = models.DateTimeField(help_text="질문을 수정한 일시", auto_now=True)
    create_date = models.DateTimeField(help_text="질문을 작성한 일시", auto_now_add=True)

    class Meta:
        db_table = "question"

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    question = models.ForeignKey(
        help_text="질문", to="Question", on_delete=models.CASCADE
    )
    content = models.TextField(help_text="답변의 내용")
    modify_date = models.DateTimeField(help_text="답변을 수정한 일시", auto_now=True)
    create_date = models.DateTimeField(help_text="답변을 작성한 일시", auto_now_add=True)

    class Meta:
        db_table = "answer"

jump-to-django/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]

jump-to-django/pybo/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]
        labels = {
            "subject": "제목",
            "content": "내용",
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]
        labels = {
            "content": "답변내용",
        }

jump-to-django/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpRequest

from .forms import UserForm


def signup(request: HttpRequest):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("index")
    else:
        form = UserForm()
    return render(request, "common/signup.html", {"form": form})

jump-to-django/pybo/views/answer_views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question, Answer
from ..forms import AnswerForm


@login_required(login_url="common:login")
def answer_create(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer: Answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            return redirect("pybo:detail", question_id=question.id)
    else:
        form = AnswerForm()
    context = {"question": question, "form": form}
    return render(request, "pybo/question_detail.html", context)


@login_required(login_url="common:login")
def answer_modify(request: HttpRequest, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            form.save()
            return redirect("pybo:detail", question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {"answer": answer, "form": form}
    return render(request, "pybo/answer_form.html", context)


@login_required(login_url="common:login")
def answer_delete(request: HttpRequest, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "삭제 권한이 없습니다.")
    else:
        answer.delete()
    return redirect("pybo:detail", question_id=answer.question.id)

jump-to-django/pybo/views/base_views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from ..models import Question


def index(request: HttpRequest):
    page = request.GET.get("page", 1)
    question_list = Question.objects.order_by("-id")
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {"question_list": page_obj}
    return render(request, "pybo/question_list.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "pybo/question_detail.html", context)

jump-to-django/pybo/views/question_views.py
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question
from ..forms import QuestionForm


@login_required(login_url="common:login")
def question_create(request: HttpRequest):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question: Question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect("pybo:index")
    else:
        form = QuestionForm()
    return render(request, "pybo/question_form.html", {"form": form})


@login_required(login_url="common:login")
def question_modify(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect("pybo:detail", question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {"form": form}
    return render(request, "pybo/question_form.html", context)


@login_required(login_url="common:login")
def question_delete(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "삭제 권한이 없습니다.")
        return redirect("pybo:detail", question_id=question.id)
    question.delete()
    return redirect("index")

jump-to-django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pico.min.css' %}">
    <title>Hello, pybo!!</title>
</head>
<body>
    <main class="container">
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    </main>
    {% block script %}
    {% endblock %}
</body>
</html>

jump-to-django/templates/common/login.html
{% extends "base.html" %}
{% block content %}
{% include "form_errors.html" %}
<form method="post" action="{% url 'common:login' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <label for="username">사용자ID</label>
    <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" />
    <label for="password">비밀번호</label>
    <input type="password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}" />
    <button>로그인</button>
</form>
{% endblock %}

jump-to-django/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url 'common:signup' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <label for="username">사용자ID</label>
    <input type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" />
    <label for="email">이메일</label>
    <input type="email" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" />
    <label for="password1">비밀번호</label>
    <input type="password" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}" />
    <label for="password2">비밀번호 확인</label>
    <input type="password" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}" />
    <button>가입하기</button>
</form>
{% endblock %}

jump-to-django/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div>
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <mark>{{ field.label }}</mark>
    {{ field.errors }}
    {% endif %}
    {% endfor %}

    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <mark>{{ error }}</mark>
    {% endfor %}
</div>
{% endif %}

jump-to-django/templates/navbar.html
<nav>
    <ul>
        <li><strong><a href="{% url 'pybo:index' %}">Pybo</a></strong></li>
    </ul>
    <ul>
        {% if user.is_authenticated %}
        <li>{{ user.username }}</li>
        <li><a href="{% url 'common:logout' %}">로그아웃</a></li>
        {% else %}
        <li><a href="{% url 'common:login' %}">로그인</a></li>
        <li><a href="{% url 'common:signup' %}">회원가입</a></li>
        {% endif %}
    </ul>
  </nav>

jump-to-django/templates/pybo/answer_form.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <!-- 에러 관리 -->
    {% include "form_errors.html" %}
    <!-- /에러 관리 -->
    <label for="content">답변 내용</label>
    <textarea type="text" name="content" id="content" row="10">{{ form.content.value | default_if_none:"" }}</textarea>
    <button type="submit">저장하기</button>
</form>
{% endblock %}

jump-to-django/templates/pybo/question_detail.html
{% extends "base.html" %}
{% load pybo_filter %}
{% block content %}
{% if messages %}
{% for message in messages %}
<mark>{{ message.tags }}</mark>
<ul><li>{{ message.message }}</li></ul>
{% endfor %}
{% endif %}
<!-- 질문 -->
<article>
    <header>
        <hgroup>
            <h4>{{ question.subject }}</h2>
            <h5>글쓴이: {{ question.author.username }}</h3>
        </hgroup>
        {% if request.user == question.author %}
        <a href="{% url 'pybo:question_modify' question.id %}">수정</a>
        <a href="javascript:if(confirm('정말로 삭제하시겠습니까?')){location.href=`{% url 'pybo:question_delete' question.id %}`}">삭제</a>
        {% endif %}
    </header>
    {{ question.content }}
    <footer>
        작성일시: {{ question.create_date }}
        {% if question.modify_date|timestamp != question.create_date|timestamp %}
        <br />
        수정일시: {{ question.modify_date }}
        {% endif %}
    </footer>
</article>

<!-- 답변 -->
<details open>
    <summary>{{ question.answer_set.count }}개의 답변이 있습니다.</summary>
    {% for answer in question.answer_set.all %}
    <p>
        <div class="grid">
            <div>{{ answer.content }}</div>
            <div>
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id %}">수정</a>
                <a href="javascript:if(confirm('정말 삭제하시겠습니까?')){location.href=`{% url 'pybo:answer_delete' answer.id %}`}">삭제</a>
                {% endif %}
            </div>
            <div>{{ answer.author.username }}</div>
            <div>
                작성일시: {{ answer.create_date}}
                {% if answer.modify_date|timestamp != answer.create_date|timestamp %}
                <br />
                수정일시: {{ answer.modify_date }}
                {% endif %}
            </div>
        </div>
    </p>
    {% endfor %}
</details>

<!-- 답변 등록 -->
<form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <label for="content">답변내용</label>
        <textarea name="content" id="content" rows="10" 
            {% if not user.is_authenticated %}disabled{% endif %}></textarea>
    <input type="submit" vaule="답변등록" />
</form>
{% endblock %}

{% block script %}
{% endblock%}

jump-to-django/templates/pybo/question_form.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <!-- 에러 관리 -->
    {% include "form_errors.html" %}
    <!-- /에러 관리 -->
    <label for="subject">제목</label>
    <input type="text" name="subject" id="subject" value="{{ form.subject.value | default_if_none:''}}">
    <label for="content">내용</label>
    <textarea type="text" name="content" id="content" row="10">{{ form.content.value | default_if_none:"" }}</textarea>
    <button type="submit">저장하기</button>
</form>
{% endblock %}

jump-to-django/templates/pybo/question_list.html
{% extends "base.html" %}
{% load pybo_filter %}
{% block content %}
<table>
    <thead>
        <tr>
           <th>번호</th> 
           <th>제목</th> 
           <th>글쓴이</th>
           <th>작성일시</th> 
        </tr>
    </thead>
    <tbody>
    {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                
                {% if question.answer_set.count > 0 %}
                <span>
                    <mark>{{ question.answer_set.count }}</mark>
                </span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
    {% else %}
        <p>질문이 없습니다.</p>
    {% endif %}

    </tbody>
</table>

<div class="grid">
    {% for page_number in question_list.paginator.page_range %}
    {% if page_number >= question_list.number|add:-3 and page_number <= question_list.number|add:3 %}
    {% if page_number == question_list.number %}
    <div><a href="?page={{ page_number }}"><button>{{ page_number }}</button></a></div>
    {% else %}
    <div><a href="?page={{ page_number }}"><button class="secondary">{{ page_number }}</button></a></div>
    {% endif %}
    {% endif %}
    {% endfor %}
</div>


<a href="{% url 'pybo:question_create' %}">질문 등록하기</a>
{% endblock %}